# These are supported funding model platforms

github: dokterbob
open_collective: ipfs-search
custom: ["https://commerce.coinbase.com/checkout/f6b4fcad-3f09-41ac-8520-81aba321d4d7", "monero:83CJdcNPXCv36kvCsLBxEsjNvYUVxMxJRNionMpcowjoeyJAoGLz421fSAHAyUycWdgABDwpZXu7CM9VwpiRerWh5Kr4RzH"]
