plugins:
  sonar-java:
    enabled: true
    config:
      minimum_severity: critical
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: true
      allow_strong_copyleft: true
exclude_patterns:
  - ".mvn/**"
