language: java

cache:
  directories:
    - $HOME/.m2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: ./mvnw verify

after_script:
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage

before_deploy: ./mvnw package -Dquarkus.package.type=uber-jar

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  draft: true

  on:
    repo: ipfs-search/tika-extractor
    tags: true

